### ISSUE TITLE
New version 1.7.24 blocks shopware order confirmation-email for SW core standard payment .... 

### ISSUE THREAD

**Issue by klausmad** [wirecard/shopware-wcs#33]
SW 5.2.7 with WCS plugin version 1.7.24 blocks shopware order confirmation-email .... if customer choose standard payment, cash, invoice, prepayment and not wirecard payment ! Critical bug, because shopware core and standard function is blocked. SW standard payment is not working if wirecard plugin is active. Maybe this is caused on the new pendinng mail functions you set in version 1.7.22 ... please try out and solve it quick. Thanks. (tested on two different shops and installations)

**Comment by suppenkelch** [comment]
Same here. Also SW 5.2.7
Confirmation-Emails are not sent.

**Comment by klausmad** [comment]
hi together, find out a workaround for version 1.7.24 until the devolper change this bug:

Go to bootstrap.php on line 873 to 881 and uncomment the lines 878 to 881 with //   in front of the line.
I checked prepayment, cash, invoice and creditcard...all is working fine now.
I am not a plugin and php developer, but I think this line cause the problem of not sendig confirmation mails if customer do not use wirecard payment. 

`    /**
     * set confirmmail after ordercreation false
     * @param Enlight_Event_EventArgs $args
     * @return bool
     */
//    public function defineSending(Enlight_Event_EventArgs $args)
//    {
//        return false;
//    }`

**Comment by rinnhofer** [comment]
the side effect on other payment methods will be as soon as possible removed and will be found in the next release. thank you for your feedback.

**Comment by rinnhofer** [comment]
We fixed the orderconfirmation-mail-problem with other payment methods in the last commit and when there was a detailed review on it there will be a new release and update in the marketplace. 
Thank your very much for your patience.

**Comment by klausmad** [comment]
hi, I am testing new version 1.7.25...the data you read out for order confirmation mail is not complete. If I take wirecard payment, the field for shipping mode is empty. But this information is seen on screen after finish the order. So please check if you import the  {$sDispatch.name}  and  {$sDispatch.description} .
If I use prepayment, the information will be sent correctly, if I take wirecard payment the shipping information is missed. Armin S. got some mails with an example from me.

**Comment by klausmad** [comment]
to solve this missed information in your confirmation mail data:

Frontend/WirecardCheckoutSeamless/Controllers/Frontend/WirecardCheckoutSeamless.php 

line  273 - 290 maybe insert please this:

'sDispatch'     => $sOrderVariables['sDispatch'],

should be the solution, please try it out, I tested it and had success mail with dispatch information, ask Armin S. he got this Mail.

**Comment by klausmad** [comment]
hi, in the next test  I did a order in my shop without VAT and I found out you do not transport the information if this order is "netto" without VAT or "brutto" with VAT included. So please check the variable 
**sNet** if you can include this information and give your confirmation mail the correct tax status. thanks.

**Comment by rinnhofer** [comment]
Thank you for your detailed testing, we updated the version 1.7.25 with the suggested changes in the newest commit and the changes will be found in the next marketplace release

**Comment by klausmad** [comment]
Hi, can you please make a version 1.7.26 for this changes...this last change ist not in the master download an not in version 1.7.25 changed.

**Comment by klausmad** [comment]
Hi, **currency is still missed in your confirmation email,** if you use wirecard payment.

for example with credit card i  got: **Gesamtkosten Brutto: 18.85**

with shopware standard payment, for example prepayment this is shown as follow:

**Gesamtkosten Brutto: 18.85 EUR**  

so Iam not sure, if your code  in Frontend/WirecardCheckoutSeamless.php  on line 288 is working ???

 'sCurrency'    => Shopware()->System()->sCurrency['currency'],  ????

Would be nice to finish this version as soon as possible .... its not so funny to make daily-testing and find daily-morning-bug.

thanks.

**Comment by klausmad** [comment]
hi, I see this should be stored and shown in the email like this:  price and currency

{$sShippingCosts}: 3,90 EUR
{$sAmount}: 45,06 EUR
{$sAmountNet}: 37,55 EUR

but if you use wirecard payment it looks like this, without the currency EUR

{$sShippingCosts}: 3.9
{$sAmount}: 18.85
{$sAmountNet}: 15.84
