### ISSUE TITLE
Plugin Version 1.7.26 - the confirmation mail to the shop owner is missed if you user wirecard payment

### ISSUE THREAD

**Issue by klausmad** [wirecard/shopware-wcs#35]
Hi, thank you for the update, but a new bug is found in 1.7.26

If you take shopware standard payment (like cash, prepayment, invoice) **the shop customer AND the shop owner get the confirmation mail.**

**If you take wirecard payment**, only the shop customer get this confirmation mail. So **the standard confirmation email to the shop owner is missed.**  So at the moment, the shop owner will not get any information about any order, which is done with wirecard payment. You must add the shop owner mailadress which is stored in the basic shopconfig for each shop. (be carefull and think on subshopfunction !!, mailadress could be different foreach).

Please solve this small bug as soon as possible. I think then we have a good and stable version.

best regards klaus

**Comment by klausmad** [comment]
update my information:

you must call and init the same function like shopware do in 
/engine/Shopware/Core/sOrder.php in yout file WirecardCheckoutSeamless.php

Check if the order mail should be sent to the shop owner > if yes > send it BCC to the mail which is in the store config.

if (!$this->config->get("sNO_ORDER_MAIL")) {
            $mail->addBcc($this->config->get('sMAIL'));

I think this must be added near / after  line 334, maybe also somehwere else...

                      // Sending confirm mail for successfull order after pending
                        $mail = Shopware()->TemplateMail()->createMail('sORDER', $context);
                        $mail->addTo($userData['additional']['user']['email']);

so please check this as soon as possible and update your file  /Frontend/WirecardCheckoutSeamless.php

**Comment by klausmad** [comment]
Hi, I tested this code, but it do not work in my demo system as it should, maybe you must call other system variable for email or we need some call on other place....., maybe sMail is not listed in your files?

I am sure you will find out the correct lines....thanks.

**Comment by klausmad** [comment]
Hi, thanks for the personal message with this workaround

$mail->addTo(Shopware()->Config()->get('mail'));

 yes, this will work, but better is:

$mail->addBcc(Shopware()->Config()->get('mail'));   because not all want to show the mailadress, who get the order confirmation as blindcopy...so better BCC as shopware standard is.

Please note: make the IF request before this line, to get the information from field sNO_ORDER_MAIL, which is located in the basic shopware settings for the orderconfirmation.

thanks for quick support....

**Comment by voodoom** [comment]
Is there an eta when this will be fixed?

**Comment by rinnhofer** [comment]
Hello,
this issue will be handled in the next release but currently we have no date fixed for this.
Temporarly you can use this code after line 333 and line 369 in file "WirecardCheckoutSeamless.php":
```
if(!Shopware()->Config()->get('sNO_ORDER_MAIL')) {
    $mail->addBcc(Shopware()->Config()->get('mail'));
}
```

Thank you for your patience
