### ISSUE TITLE
Not compatible with shopware 5.3.7

### ISSUE THREAD

**Issue by JSchmieta** [wirecard/shopware-wcs#75]
Compatibility with current Shopware version 5.3.7 not verified

**Comment by JSchmieta** [comment]
Just not verified...

Kind regards
Jörn 

Am 30. Januar 2018 14:47:42 MEZ schrieb klausmad <notifications@github.com>:
>Hi, "Not compatible with shopware 5.3.7 ???" Is there any known problem
>with the function of WCS under SW 5.3.7. or is it just "not verfied"
>for SW 5.3.7.  BR Klaus
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wirecard/shopware-wcs/issues/75#issuecomment-361597986

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jakubpolomsky** [comment]
as our [guides ](https://guides.wirecard.com/shop_plugins:wcs:shopware:start) state, this plugin was lastly tested with the version 5.3.4, it is possible that the plugin is working with the aforementioned version, it is just not officially tested

Kind regards,
Wirecard

**Comment by tomazpu** [comment]
Hello, 
the plugin has been tested with the 5.3.7 shopware version and there where no compatibility issues found.

Kind regards
