### ISSUE TITLE
Remove appendSession Usage

### ISSUE THREAD

**Issue by shyim** [wirecard/shopware-wcs#83]
https://github.com/wirecard/shopware-wcs/blob/master/Frontend/WirecardCheckoutSeamless/Controllers/Frontend/WirecardCheckoutSeamless.php#L148

appendSession should be not used anymore. This functionality has been removed with 5.5.7

**Comment by jakubpolomsky** [comment]
Hello,

we are already working on this issue. As our plugin relies on the session to create the order, the changeset will be a bit longer than just removing this line. Thank you for noticing this, the updates will follow soon.

Kind regards

**Comment by rinnhofer** [comment]
Hello @shyim ,
with our last release appendSession was removed. I will close this issue now.
https://github.com/wirecard/shopware-wcs/releases/tag/1.10.15

Kind regards
Wirecard Plugin Team
